<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>273dc7be-7cba-42c7-91de-6a4c7d325d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cart_image > img[alt=&quot;Combo 2 Lốc Cà Phê Sữa Highlands Coffee 185ml/lon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div/div[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a7ec4d0e-40ba-469c-aaef-3c8024a48504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bizweb.dktcdn.net/thumb/medium/100/465/740/products/web-83-sku-07.png</value>
      <webElementGuid>27c6248b-1090-4717-8d7e-ee2b36ce6eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Combo 2 Lốc Cà Phê Sữa Highlands Coffee 185ml/lon</value>
      <webElementGuid>dcd74846-1e7a-4c7e-8e1e-f65a486a3ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-sidebars&quot;)/div[@class=&quot;evo-cart-content&quot;]/div[@class=&quot;cart_body&quot;]/div[@class=&quot;clearfix cart_product productid-107488287&quot;]/a[@class=&quot;cart_image&quot;]/img[1]</value>
      <webElementGuid>39b6a739-607d-4cea-9576-5e0a50ae603f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-sidebars']/div/div[2]/div/a/img</value>
      <webElementGuid>747c6527-3dc9-4553-b0d0-5da096c67560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Combo 2 Lốc Cà Phê Sữa Highlands Coffee 185ml/lon'])[2]</value>
      <webElementGuid>940fadd6-5058-4128-b8ca-c156c82046a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>2d203fcf-ccbf-43c2-a81c-b9b3129f934e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bizweb.dktcdn.net/thumb/medium/100/465/740/products/web-83-sku-07.png' and @alt = 'Combo 2 Lốc Cà Phê Sữa Highlands Coffee 185ml/lon']</value>
      <webElementGuid>994821b0-866c-415e-a001-fcb3738c1528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
