<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Lines</name>
   <tag></tag>
   <elementGuidId>20a285a6-6a25-4695-a107-2425916d2469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qtyItem114503628</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;qtyItem114285343&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40b4e5e7-cdc6-46c9-b050-5f6beba2bbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>855ae365-8d38-4116-89e7-a5fab0e9478b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f1df1228-530a-4d69-9049-fa5d3d9d3663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17332110-1b49-4946-b5ed-189c3ad0fb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text number-sidebar qtyItem114503628</value>
      <webElementGuid>b4bdf008-617b-4333-b150-0df2d0b49e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qtyItem114503628</value>
      <webElementGuid>78aeda28-fe05-41f5-91d5-6451545fac90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lines</value>
      <webElementGuid>ffb7efd6-18bb-4b53-80bf-1aeb601cf405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>090df3be-9cb6-41ab-a05d-c154bd8bfa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c95d33df-260c-419e-aef8-89c2d6288c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qtyItem114503628&quot;)</value>
      <webElementGuid>0603335f-feca-4440-a076-c057c8638b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qtyItem114503628']</value>
      <webElementGuid>5f0faa94-ece5-4fe5-9c79-1cfe7006fd17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-sidebars']/div/div[2]/div/div/div[2]/div/div/div/div/input[2]</value>
      <webElementGuid>42f075da-db00-4039-8fa7-9cc849999188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>efd5dac8-28bf-44ff-852e-1527da200a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'qtyItem114503628' and @name = 'Lines']</value>
      <webElementGuid>ad5439fa-985b-4371-bf1b-d87b14d70079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qtyItem93343594']</value>
      <webElementGuid>9f75e847-5999-4964-ac0b-8bf80b160b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'qtyItem93343594' and @name = 'Lines']</value>
      <webElementGuid>8e056f69-9832-4dd8-ab30-a2474d12310e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
