<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_339.000</name>
   <tag></tag>
   <elementGuidId>034e89ad-2136-48cc-ba77-6a6c85c9a3ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-sidebars']/div/div[3]/div/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.total-price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>927327dc-55ea-457f-a8ca-db14016ac4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total-price</value>
      <webElementGuid>4d741dc0-b9cd-43f1-8893-9419c426ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>339.000₫</value>
      <webElementGuid>2d85d575-362e-4c16-913e-53a5328f0624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-sidebars&quot;)/div[@class=&quot;evo-cart-content&quot;]/div[@class=&quot;cart-footer&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;cart__subtotal&quot;]/div[@class=&quot;text-right cart__totle&quot;]/span[@class=&quot;total-price&quot;]</value>
      <webElementGuid>b67fcbaf-123e-4e38-8dff-ab3373d012ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-sidebars']/div/div[3]/div/div/div[2]/span</value>
      <webElementGuid>d48baa37-8fda-404e-9e2c-28e6a8a1a1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền:'])[1]/following::span[1]</value>
      <webElementGuid>cf44962d-e4d4-4a04-b81d-5066f312f5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ sản phẩm'])[2]/following::span[1]</value>
      <webElementGuid>9b72b3c6-6c6a-4bee-b83a-ff48bc1d3923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán'])[1]/preceding::span[1]</value>
      <webElementGuid>6ff9bbce-e58f-48d0-8746-e9c9a23be12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm sản phẩm'])[1]/preceding::span[1]</value>
      <webElementGuid>37902d61-aed8-4554-b35f-7d12a3e3bf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='339.000₫']/parent::*</value>
      <webElementGuid>9927e914-68f0-4ea4-918d-f107b97b2c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/span</value>
      <webElementGuid>2816dd5d-93ac-40f0-aa71-e45786e8063e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '339.000₫' or . = '339.000₫')]</value>
      <webElementGuid>02e20a1d-5caa-4f54-84d3-b4c0791e826d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
