<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Khng th load ph vn chuyn. Vui lng th _3d47c1</name>
   <tag></tag>
   <elementGuidId>67112e87-d92e-4080-9ed3-d9dd5520a455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shippingMethod-699527_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shippingMethod-699527_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00b6598f-2b45-46eb-a087-363ed4ba9b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0958e100-e1a8-42cf-8c0c-dacf365fa955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>b8af6448-db82-432c-9988-8c6efa37cbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shippingMethod</value>
      <webElementGuid>c4d565e2-37f0-45a7-a9e8-1c4b9e57b154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingMethod-699527_0</value>
      <webElementGuid>6ab5db96-2466-45da-8f6c-c26ce5196789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>699527_0,25.000 VND</value>
      <webElementGuid>958c7085-1910-4262-bd5f-e43cd8d29b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>shippingMethod</value>
      <webElementGuid>d1920ef2-6e77-433f-8ccc-e7186d49312e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingMethod-699527_0&quot;)</value>
      <webElementGuid>2994fa99-2b2b-4249-bb4a-a4888559b6fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shippingMethod-699527_0']</value>
      <webElementGuid>459b286e-8ca4-4825-8c69-58c49f06eace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shippingMethodList']/div[3]/div/div/div/input</value>
      <webElementGuid>0ad5c251-ac3c-4e5b-a411-ba635bf8b701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>348dbd5a-37f3-4431-9056-d018541fe8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'shippingMethod' and @id = 'shippingMethod-699527_0']</value>
      <webElementGuid>3501dc7a-e7d3-4d84-a137-3affc95090de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
