<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Thanh ton qua V in t MoMo_paymentMethod</name>
   <tag></tag>
   <elementGuidId>45aff6a0-6b5f-41de-90b0-dc2004b069d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentMethod-548276</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentMethod-548276']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85786c81-adfa-45ef-a016-f40d815a2825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethod</value>
      <webElementGuid>6cc7fc53-2c81-4ee3-9f36-ca293d3e0e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentMethod-548276</value>
      <webElementGuid>93ad9b87-5ecf-44fc-982e-87615f76075a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5d59a4be-6c47-42ce-82aa-dbb9b7e520aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>3db5caff-b464-4637-af67-f6ada9745638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>paymentMethod</value>
      <webElementGuid>44c90e22-2834-458a-bc8c-a23f82e2dd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>548276</value>
      <webElementGuid>56bc8fae-84c6-4c97-96ec-04504a4452f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provider-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0604e96b-1a4d-4482-baac-2acdb870ccd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod-548276&quot;)</value>
      <webElementGuid>a0d088cd-e236-4f18-86bd-050d927de12c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentMethod-548276']</value>
      <webElementGuid>d8162e3d-7b6c-49b3-9c16-5324923959de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/div/main/div/article/div[2]/section[2]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>8565ee51-9bd9-4a7a-84e7-f04312fbeb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>937b0e11-7d53-4675-847b-6222a63efc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'paymentMethod' and @id = 'paymentMethod-548276' and @type = 'radio']</value>
      <webElementGuid>b7a8e533-f3c7-4ea8-bd48-e38d0edfafb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
