<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S in thoi_billingPhone</name>
   <tag></tag>
   <elementGuidId>8d848277-8de3-4e5b-9bf7-12e428348798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6addd1f1-24d5-4c37-a4c2-decae275ca4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingPhone</value>
      <webElementGuid>cacf7517-21d6-4fab-8cd1-9d144884f4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingPhone</value>
      <webElementGuid>6c8bfb3f-4ad3-4079-a0cb-6b24b9afe787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>10f653bd-afb7-4ed3-b9aa-18e32d42791c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field__input</value>
      <webElementGuid>f8402329-e349-4f3c-ae74-2716a1fd129e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>billing.phone</value>
      <webElementGuid>eedee97f-21ff-49f2-a2b4-d9b92457912f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingPhone&quot;)</value>
      <webElementGuid>f336c237-ade2-4416-a0b9-627d5782bd46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingPhone']</value>
      <webElementGuid>c06e8cef-5c90-46d5-b2a6-4c381a76b6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/div/main/div/article/div/section/div[2]/div/div[3]/div/input</value>
      <webElementGuid>1c8c224c-df24-44af-8345-d7d040139ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2a2fdc52-ef1c-4c22-adca-872b93a2e350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'billingPhone' and @id = 'billingPhone' and @type = 'tel']</value>
      <webElementGuid>ff40e35c-2e3d-4029-8d17-e99470e8f4da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
