<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Thanh ton_paymentMethod</name>
   <tag></tag>
   <elementGuidId>138f32d9-cc5e-47de-91ed-028010db7b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentMethod-727589</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentMethod-727589']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4e3a0fd-a053-4b25-9996-085acb3fb907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethod</value>
      <webElementGuid>5a26debb-d5ce-481e-a031-282c6baaad4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentMethod-727589</value>
      <webElementGuid>c1c54bdc-8fdf-442b-88f2-03b138d8c839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>23f13e61-1cfe-4efd-992d-47775f7b2d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>254685fd-fa7b-4542-aeac-e36b6cb23553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>paymentMethod</value>
      <webElementGuid>293a94eb-7e03-4d36-88e2-25cbbb057b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>727589</value>
      <webElementGuid>7349adee-e6b7-42d0-9368-5d14b9a07149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provider-id</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>e51b5d06-1ffd-40d4-97f2-97fa2aa2d8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod-727589&quot;)</value>
      <webElementGuid>ab83c29a-4642-4641-9ba9-18578b903e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentMethod-727589']</value>
      <webElementGuid>a2577237-2469-43dc-9fd1-232eb73fc36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutForm']/div/main/div/article/div[2]/section[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>9fccdcf1-1623-4e41-9a75-bc2702ec4057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>e55e2761-dbdc-4525-8555-04869e4226fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'paymentMethod' and @id = 'paymentMethod-727589' and @type = 'radio']</value>
      <webElementGuid>384bab97-f804-42c9-a6da-d23a22567366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
