<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp m gim gi_reductionCode</name>
   <tag></tag>
   <elementGuidId>c1574b43-833c-4d5e-8125-964ddd421b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reductionCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reductionCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>375a1421-a6c3-4d29-a393-208bb4e8a441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reductionCode</value>
      <webElementGuid>853fb8b6-0fda-481a-9301-6cc40e6e06cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reductionCode</value>
      <webElementGuid>218a7498-b70e-4783-b7c3-51bd194f9e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26eef734-7d21-4c7d-9a00-564707d29ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field__input</value>
      <webElementGuid>c2be6c95-1fcf-416b-8841-73b1fd6505fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e566621-f222-42e9-9d35-ad6ddd02d15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind-disabled</name>
      <type>Main</type>
      <value>isLoadingReductionCode</value>
      <webElementGuid>213aa8ec-3ad2-4508-b0da-cb9bdf6ea22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind-event-keypress</name>
      <type>Main</type>
      <value>handleReductionCodeKeyPress(event)</value>
      <webElementGuid>90fcd230-1fcf-48c4-8b85-74a6b80db067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-define</name>
      <type>Main</type>
      <value>{reductionCode: null}</value>
      <webElementGuid>4e1700c1-3508-41f6-a584-d57743901752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>reductionCode</value>
      <webElementGuid>95dac02f-4a66-448d-8b88-fd090bbc3167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reductionCode&quot;)</value>
      <webElementGuid>9488b027-2c22-4853-a912-a634a7fdc732</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reductionCode']</value>
      <webElementGuid>28aa734c-6fa3-48e5-b2bf-9e2ee5c65e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='discountCode']/div/div/div/div/div/input</value>
      <webElementGuid>18b5a062-44cc-4107-843b-c2296de5cb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>152ebc1c-87b8-4780-9847-d6af28a94f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'reductionCode' and @id = 'reductionCode' and @type = 'text']</value>
      <webElementGuid>b8536abc-044a-43cb-b4af-a782e5fd641d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
