<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email</name>
   <tag></tag>
   <elementGuidId>af810141-b533-4a2d-880d-ed88a263f2ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customer_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06ee6a19-7af5-41eb-a6bf-1c6440e398f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5eef2500-2d97-474e-b80c-e9c9a58405f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập Địa chỉ Email</value>
      <webElementGuid>9cf5fefd-95ef-4473-b06f-f94315f22d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>98a45451-cd5b-4d2e-b113-51fb76defb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>c7b4f294-d374-4115-8be5-e12684fa61a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>29031dcb-a986-45cb-a946-3bdcd3a112cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_email</value>
      <webElementGuid>d13a516e-6be7-4a09-bb79-a0611d95f01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9b824995-aefd-4406-b9ff-e99691803abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,63}$</value>
      <webElementGuid>d2adb1bd-e8d1-45a3-ad9e-2c24707b2df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-error-msg</name>
      <type>Main</type>
      <value>Email sai định dạng</value>
      <webElementGuid>a9e13899-156b-40b2-96b0-8aaa993540bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_email&quot;)</value>
      <webElementGuid>94ff319a-cb08-43e3-8f52-d860b9caf90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_email']</value>
      <webElementGuid>bf01a022-adc0-4a9a-bd15-26223f4de385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[2]/fieldset/input</value>
      <webElementGuid>56400d96-7ae3-47bc-aee7-de99d40417dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>74aab2c0-e84e-4099-8a13-e57bc1e5043c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nhập Địa chỉ Email' and @type = 'email' and @name = 'email' and @id = 'customer_email']</value>
      <webElementGuid>b3037c28-a4f6-4271-936d-20845dcb1231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
