<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thng 24 Lon C Ph Sa Highlands Coffee 235mllon</name>
   <tag></tag>
   <elementGuidId>f0612760-d7f7-4da9-82bf-c71f7e21a6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Thùng 24 Lon Cà Phê Sữa Highlands Coffee 235ml/lon')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08792e7b-ed99-4e62-a972-946c955572b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/thung-24-lon-ca-phe-sua-highlands-coffee-235ml-lon</value>
      <webElementGuid>49688890-c8e8-459d-852d-118102e8ba07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thùng 24 Lon Cà Phê Sữa Highlands Coffee 235ml/lon</value>
      <webElementGuid>2d651ca0-eb6f-44f9-b39a-c7068a313547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>40f8c166-429e-4c00-bbd2-c626f43a7986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7dbb5a08-c8e0-4e5c-8b0e-a8582c17c9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thùng 24 Lon Cà Phê Sữa Highlands Coffee 235ml/lon</value>
      <webElementGuid>927e1579-f455-46cc-805a-84d69dab46d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;index&quot;]/section[@class=&quot;awe-section-5&quot;]/div[@class=&quot;container evo_block-product&quot;]/div[@class=&quot;evo_section_product evo-block-product slick-frame slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;item slick-slide slick-active&quot;]/form[@class=&quot;variants product-action has-validation-callback&quot;]/div[@class=&quot;evo-product-new&quot;]/a[@class=&quot;title&quot;]</value>
      <webElementGuid>3afe4753-dd9d-4662-ade4-5f975b9b4ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Thùng 24 Lon Cà Phê Sữa Highlands Coffee 235ml/lon')])[2]</value>
      <webElementGuid>73114f43-cbd4-4037-95b6-ff14fa685c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[NHẬN TÚI CÓI THỜI TRANG] Cà Phê Bột Truyền Thống Highlands Coffee 1KG'])[2]/following::a[2]</value>
      <webElementGuid>75dbe255-f3aa-41f1-b356-4c94569bb04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thùng 48 hộp Cà phê Sữa Highlands Coffee Tetra pack (180ml /hộp)'])[1]/preceding::a[2]</value>
      <webElementGuid>8b451b50-aaa2-4c2c-bf8b-3e079b83bc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/thung-24-lon-ca-phe-sua-highlands-coffee-235ml-lon')])[4]</value>
      <webElementGuid>0719e526-946c-4ef6-98fc-5be69b2e874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/div/div[2]/form/div/a[2]</value>
      <webElementGuid>7708cdff-9736-429a-a5c5-0b7297d41f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/thung-24-lon-ca-phe-sua-highlands-coffee-235ml-lon' and @title = 'Thùng 24 Lon Cà Phê Sữa Highlands Coffee 235ml/lon' and (text() = 'Thùng 24 Lon Cà Phê Sữa Highlands Coffee 235ml/lon' or . = 'Thùng 24 Lon Cà Phê Sữa Highlands Coffee 235ml/lon')]</value>
      <webElementGuid>67f4b2db-cc4c-4033-8012-d78157a0d2b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
