<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thanh ton</name>
   <tag></tag>
   <elementGuidId>ca21a481-b2d6-4ce1-bf0b-9b3ce963e9c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-proceed-checkout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-proceed-checkout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c56a84a-c69f-4a65-a448-c17c136173ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/checkout'</value>
      <webElementGuid>bf6a793a-7125-4007-b13f-88b96d5eb408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23637ac4-0d67-4ede-95da-ae8dffb3523a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn btn-default cart__btn-proceed-checkout</value>
      <webElementGuid>11b4c778-d849-483f-8bd5-b49e3baa716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-proceed-checkout</value>
      <webElementGuid>c8bfe97e-ba4d-4810-942b-40a4da210a20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thanh toán</value>
      <webElementGuid>8e065693-d5b0-4ceb-9cd1-8b2880fb09b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanh toán</value>
      <webElementGuid>343d0caa-f313-44c8-8175-b6523380cc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-proceed-checkout&quot;)</value>
      <webElementGuid>e6432d34-6862-4434-9d28-b5ff8b71d3c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-proceed-checkout']</value>
      <webElementGuid>b7a51d7f-51d3-44a5-9bdb-58c9bdc434c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-sidebars']/div/div[3]/div[2]/button</value>
      <webElementGuid>01d4f64f-9b13-4d3f-85d9-e78658fdfe29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền:'])[1]/following::button[1]</value>
      <webElementGuid>421d4350-5ee6-4639-8aec-1b1e1cb55439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ sản phẩm'])[1]/following::button[1]</value>
      <webElementGuid>abce508d-00be-4ab4-a496-c703cc76a20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm sản phẩm'])[1]/preceding::button[1]</value>
      <webElementGuid>670e9d39-b7f9-48e8-9828-6afbcd0343a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Messenger'])[1]/preceding::button[3]</value>
      <webElementGuid>6ec94a31-26fd-4418-842d-543e60dcc099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanh toán']/parent::*</value>
      <webElementGuid>2ee4f5fd-181a-4133-b9fe-669395e0b0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>745203b5-2d97-4091-8585-fbd7743f742f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-proceed-checkout' and @title = 'Thanh toán' and (text() = 'Thanh toán' or . = 'Thanh toán')]</value>
      <webElementGuid>f24a475e-0a40-4e6b-a40b-2d6b3573f429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
