<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Chng trnh  ht hn</name>
   <tag></tag>
   <elementGuidId>051d5907-167c-4bfc-b762-e1a0f6effe8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pro-down > div.count-down > div.timer-view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[2]/following::div[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf3b0282-3567-4502-a873-76be482594c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timer-view</value>
      <webElementGuid>fd3010b9-0490-49c7-858a-ddac8712135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Chương trình đã hết hạn</value>
      <webElementGuid>b822981d-3d2b-4d78-b6e5-60399ab10bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;index&quot;]/section[@class=&quot;awe-section-4&quot;]/section[@class=&quot;section_flash_sale&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;box_mail&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12 col-xs-12 box-pro&quot;]/div[@class=&quot;evo_section_product evo-block-sale slick-frame slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;item slick-slide slick-current slick-active&quot;]/form[@class=&quot;variants product-action has-validation-callback&quot;]/div[@class=&quot;evo-product-new&quot;]/div[@class=&quot;pro-down&quot;]/div[@class=&quot;count-down&quot;]/div[@class=&quot;timer-view&quot;]</value>
      <webElementGuid>23e0b64a-d348-46f7-9706-255cb0af6027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-countdown</name>
      <type>Main</type>
      <value>countdown</value>
      <webElementGuid>273422b4-a841-4897-b603-15e2e169adec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date</name>
      <type>Main</type>
      <value>04-19-2024-23-59-59</value>
      <webElementGuid>9d7b3ce2-0427-4912-a0ea-51f16d782a28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[2]/following::div[13]</value>
      <webElementGuid>c63702eb-d75d-47ea-95c3-db23665f3872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xem tất cả'])[1]/following::div[15]</value>
      <webElementGuid>15c7c074-9acd-49cd-9093-864706082c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/div</value>
      <webElementGuid>71a09f87-83ac-49b2-b42b-5992351a04e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Chương trình đã hết hạn' or . = ' Chương trình đã hết hạn')]</value>
      <webElementGuid>7d3b8036-18ec-462d-a4db-a2c2f761beb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Combo trọn vị] 3 vị cà phê Highlands Coffee 200g'])[3]/following::div[10]</value>
      <webElementGuid>63daef7f-7462-4cdb-8f82-00f51021a832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMBO 2 Gói Cà Phê Rang Xay Truyền Thống Highlands Coffee 200g/gói'])[3]/preceding::div[3]</value>
      <webElementGuid>50c8e227-1e24-45df-86a1-42aa1a07c139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div/div/div/div[3]/form/div/div[3]/div/div/div</value>
      <webElementGuid>e53e8ce0-113d-4372-9f84-97da82795718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
