<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Chn mua_add_img</name>
   <tag></tag>
   <elementGuidId>4fc77742-71b2-488f-89e0-319a3804df3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Chọn mua'])[32]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd1b1ab0-1092-47a6-a7c8-8f1ca2a654af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add_img</value>
      <webElementGuid>9a43cf84-dfa7-4e5d-bfdf-a6032226f25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>d1dd3752-4edf-4b72-8df4-5cc89ed38ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>18148422-5d01-4661-84aa-e2d46beb65e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//bizweb.dktcdn.net/100/465/740/themes/884110/assets/shopping-bag.png?1716966710754</value>
      <webElementGuid>ac592889-8a74-441b-bc1f-fc20a432803a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Chọn mua</value>
      <webElementGuid>22b8d9e0-0942-4781-a3f7-444ee5dd0c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;index&quot;]/section[@class=&quot;awe-section-7&quot;]/div[@class=&quot;container evo_block-product&quot;]/div[@class=&quot;evo_section_product evo-block-product slick-frame slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;item slick-slide slick-active&quot;]/form[@class=&quot;variants product-action has-validation-callback&quot;]/div[@class=&quot;evo-product-new&quot;]/div[@class=&quot;product-action&quot;]/div[@class=&quot;group_action&quot;]/button[@class=&quot;btn-buy btn-cart btn-left btn btn-views left-to add_to_cart active&quot;]/img[@class=&quot;add_img&quot;]</value>
      <webElementGuid>a1113999-2319-4e17-9349-d4fa54438dd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Chọn mua'])[32]</value>
      <webElementGuid>9c6d8dea-7f67-440c-aec0-ded2e58a9cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/div/div/div/div/div[2]/form/div/div[5]/div/button/img</value>
      <webElementGuid>151bac40-855d-4d46-a7d3-93d9b9057307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bizweb.dktcdn.net/100/465/740/themes/884110/assets/shopping-bag.png?1716966710754' and @alt = 'Chọn mua']</value>
      <webElementGuid>487ec1e5-0a4a-45c4-941e-a392598b26aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Chọn mua'])[2]</value>
      <webElementGuid>45948f3e-dc5b-4046-bd3d-41ae8acc74ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div[4]/div/button/img</value>
      <webElementGuid>302afc01-ebce-4f05-b7c1-b68faa524c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//bizweb.dktcdn.net/100/465/740/themes/884110/assets/shopping-bag.png?1713718122584' and @alt = 'Chọn mua']</value>
      <webElementGuid>fd1b7c1f-7e9c-4f79-bf2b-caa6bd1572ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
