<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cpg.customerservicevtijs.com_query</name>
   <tag></tag>
   <elementGuidId>f4c78609-1d9e-46d2-aace-9b169c41ac5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='query']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;query&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55d7f586-a31a-429c-903d-d6c558bb89f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08585baf-0974-4db2-b1f3-7f0fc85ffe00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tìm sản phẩm</value>
      <webElementGuid>c8c56d3e-5c69-438c-9ef3-e7859b89f65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>86391a70-7f89-4dc2-8a64-5190f1e3368a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-auto form-control</value>
      <webElementGuid>f8e2fcd5-5b29-430d-a190-d0e4665ce916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm...</value>
      <webElementGuid>6386ab1a-4ebf-41ab-8a07-eaed5438d5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d2152dd5-fc41-4992-9ffa-5ca1fb330b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;index&quot;]/header[@class=&quot;header&quot;]/div[@class=&quot;top-hea-menu&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center evo-header-padding&quot;]/div[@class=&quot;col-lg-6 col-md-5 evo-search-desktop d-lg-block d-none&quot;]/div[@class=&quot;evo-searchs focus&quot;]/form[@class=&quot;evo-header-search-form has-validation-callback&quot;]/input[@class=&quot;search-auto form-control&quot;]</value>
      <webElementGuid>bfef1c1b-0146-45ff-a881-a07f78a04c9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='query']</value>
      <webElementGuid>7b32a2e2-f261-4d10-a416-4f074b7d8c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d702513e-bc93-44da-b650-8f09aaa0d211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'query' and @placeholder = 'Tìm sản phẩm...']</value>
      <webElementGuid>5a4da214-6548-4704-8042-0b521b7bb594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
