<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xa</name>
   <tag></tag>
   <elementGuidId>c1d76099-2849-4270-a90a-9a8478afe4bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-link.btn-item-delete.remove-item-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='btn btn-link btn-item-delete remove-item-cart' and @title='Xóa']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9c5e829-1117-43b2-8802-14f4419e09ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>b09182e6-c5fc-4587-9881-9d59523e83e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link btn-item-delete remove-item-cart</value>
      <webElementGuid>c2dfb64d-5b9c-411f-a2f2-52273da1949a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>90231663</value>
      <webElementGuid>1745507e-6b9b-474d-a678-fbdf8c0c58c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Xóa</value>
      <webElementGuid>49f6efdb-0896-47d9-87a1-41f38599ae8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xóa</value>
      <webElementGuid>ca38ce53-01e8-4c5e-97ed-c8a5cd2187e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart&quot;)/div[@class=&quot;cart page_cart cart_des_page hidden-xs-down row&quot;]/div[@class=&quot;col-lg-12 cart-col-1&quot;]/div[@class=&quot;cart-tbody&quot;]/div[@class=&quot;row shopping-cart-item productid-90231663&quot;]/div[@class=&quot;col-right col-lg-9&quot;]/div[@class=&quot;box-info-product&quot;]/p[@class=&quot;action&quot;]/a[@class=&quot;btn btn-link btn-item-delete remove-item-cart&quot;]</value>
      <webElementGuid>729ce270-c1fd-4ce5-821e-e9a7a58d3930</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart']/div/div/div/div/div[2]/div/p[4]/a</value>
      <webElementGuid>5ec109c2-7b8a-470d-a934-609ba9643315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xóa')]</value>
      <webElementGuid>060d8991-664a-429a-805e-038a55a804ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[NHẬN TÚI CÓI THỜI TRANG] Cà Phê Bột Truyền Thống Highlands Coffee 1KG'])[1]/following::a[1]</value>
      <webElementGuid>0a1ff5a5-701d-4980-8c60-c9144b72f118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::a[1]</value>
      <webElementGuid>5afc80c2-bf9e-4657-b534-0e2a7f32ce6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/preceding::a[1]</value>
      <webElementGuid>8e3776f7-a5c8-4293-be14-9b9d601e191a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xóa']/parent::*</value>
      <webElementGuid>028bd85c-da10-495a-b8c4-96c7fc906fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>f81e3c77-3735-49e3-b0b0-401862370352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/a</value>
      <webElementGuid>637cb6a5-9602-4521-8903-6501db774783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @title = 'Xóa' and (text() = 'Xóa' or . = 'Xóa')]</value>
      <webElementGuid>50e8f530-5432-4707-83cb-d62160248bed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
