<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>97a0eb6e-8495-4a1b-9865-1c65de3ed249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.increase_pop.items-count.btn-plus.btn.btn-default.bootstrap-touchspin-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3cab8965-4e1a-48eb-8418-dcb9fb09f22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var result = document.getElementById('qtyItem93375461'); var qtyItem93375461 = result.value; if( !isNaN( qtyItem93375461 )) result.value++;return false;</value>
      <webElementGuid>30c73fcc-fa6f-463b-8361-093860feb6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>increase_pop items-count btn-plus btn btn-default bootstrap-touchspin-up</value>
      <webElementGuid>67bfe852-7090-4574-ba61-ce3daa263e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>818dba4d-52c7-4dde-bdd8-7e0e5e79ada4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>d49f28dc-c090-40d9-ab53-da202f7b9d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart&quot;)/div[@class=&quot;cart page_cart cart_des_page hidden-xs-down row&quot;]/div[@class=&quot;col-lg-12 cart-col-1&quot;]/div[@class=&quot;cart-tbody&quot;]/div[@class=&quot;row shopping-cart-item productid-93375461&quot;]/div[@class=&quot;col-right col-lg-9&quot;]/div[@class=&quot;quantity-block&quot;]/div[@class=&quot;bootstrap-touchspin&quot;]/div[@class=&quot;input-group-btn&quot;]/button[@class=&quot;increase_pop items-count btn-plus btn btn-default bootstrap-touchspin-up&quot;]</value>
      <webElementGuid>2a7dd6bb-ab8f-462a-8d45-1b624e6ff883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>bfd89ec7-216a-42d0-8a2b-ef8b1fccf363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart']/div/div/div/div/div[2]/div[3]/div/div/button</value>
      <webElementGuid>c885faca-4f81-4793-a780-31bfee646467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[1]/following::button[1]</value>
      <webElementGuid>c39863d7-87a1-4139-a598-494f76a06eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Tặng thêm gói Truyền Thống 200g] Cà Phê Bột Truyền Thống 1kg'])[1]/following::button[1]</value>
      <webElementGuid>f837ef29-3136-4188-81dc-669e19b2aa09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/preceding::button[1]</value>
      <webElementGuid>cd2a11d7-e471-499a-92a6-49a5bd75a723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp tục mua hàng'])[1]/preceding::button[2]</value>
      <webElementGuid>17aa1748-be7d-4355-8b39-79243b705ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>169e08f2-1dd2-4dad-b645-d8ca4b2fb620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>8b42c141-c1af-4467-9be4-fe1325b0bb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+' or . = '+')]</value>
      <webElementGuid>488946be-d821-4cff-b06c-2644658c3a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
