<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>29a74824-6283-4800-a84c-20f197c02569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.reduced_pop.items-count.btn-minus.btn.btn-default.bootstrap-touchspin-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6cc733f-a7d0-4b97-a22d-f352b84f2349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var result = document.getElementById('qtyItem93375461'); var qtyItem93375461 = result.value; if( !isNaN( qtyItem93375461 ) &amp;&amp; qtyItem93375461 > 1 ) result.value--;return false;</value>
      <webElementGuid>f65f527b-c5fb-45ae-8f11-213df04dd701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reduced_pop items-count btn-minus btn btn-default bootstrap-touchspin-down</value>
      <webElementGuid>604a239c-6f37-411e-8423-fb599c65331d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee200a24-9650-4cd4-b166-bd9148e700c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>–</value>
      <webElementGuid>edcc1b7b-852d-40ee-8c21-6b39d02b7d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart&quot;)/div[@class=&quot;cart page_cart cart_des_page hidden-xs-down row&quot;]/div[@class=&quot;col-lg-12 cart-col-1&quot;]/div[@class=&quot;cart-tbody&quot;]/div[@class=&quot;row shopping-cart-item productid-93375461&quot;]/div[@class=&quot;col-right col-lg-9&quot;]/div[@class=&quot;quantity-block&quot;]/div[@class=&quot;bootstrap-touchspin&quot;]/div[@class=&quot;input-group-btn&quot;]/button[@class=&quot;reduced_pop items-count btn-minus btn btn-default bootstrap-touchspin-down&quot;]</value>
      <webElementGuid>6ae5c3d8-4d45-464b-a8d4-9fba7091fbf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>51033789-733a-4de8-8286-65b6a921b912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart']/div/div/div/div/div[2]/div[3]/div/div/button[2]</value>
      <webElementGuid>d2436a39-4352-4796-a387-f6afe5ef036f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>987566cb-5db1-47e5-a53f-e5b1985bd73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xóa'])[1]/following::button[2]</value>
      <webElementGuid>9ed8d1f5-64f8-4c04-8f14-122d3e89619f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiếp tục mua hàng'])[1]/preceding::button[1]</value>
      <webElementGuid>da1487c4-ab97-46fe-b518-546621476e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạm tính:'])[1]/preceding::button[1]</value>
      <webElementGuid>8cc04552-3d2f-4683-8b44-9b5d8104f2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='–']/parent::*</value>
      <webElementGuid>17c12a37-00f0-4890-b4d7-92f92e17cd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button[2]</value>
      <webElementGuid>b13cf7e9-d2f9-47de-8d3a-7f295b82445e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '–' or . = '–')]</value>
      <webElementGuid>18735b66-95bc-4e58-9e2b-fcfc9371cf4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
