<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tip tc mua hng</name>
   <tag></tag>
   <elementGuidId>0389b4c8-d2ad-4c22-bec6-fb714c3e2a40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-proceed-continues-mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(text(),'Tiếp tục mua hàng')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b972673d-8551-4bfe-a831-266ce9b046de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-proceed-continues-mobile</value>
      <webElementGuid>de615e0c-2aff-40a5-a8f1-f3d864e85e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tiếp tục mua hàng</value>
      <webElementGuid>2fe4ab65-b149-4cce-af36-25963f41f2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c084df7a-9e17-45ee-9dae-2125d58f8f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location.href='/collections/all'</value>
      <webElementGuid>c4103b30-16e6-4e2a-94ba-29602f8a2322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiếp tục mua hàng</value>
      <webElementGuid>9f429067-9000-4dea-8da3-e7a81bf7d243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cart&quot;]/div[@class=&quot;container white collections-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9&quot;]/div[@class=&quot;shopping-cart&quot;]/div[@class=&quot;d-lg-none d-xl-none&quot;]/div[@class=&quot;cart-mobile&quot;]/form[@class=&quot;margin-bottom-0 has-validation-callback&quot;]/div[@class=&quot;header-cart-content&quot;]/div[@class=&quot;header-cart-price&quot;]/button[@class=&quot;btn btn-proceed-continues-mobile&quot;]</value>
      <webElementGuid>13702d78-4063-411f-9d68-5698dba18b61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>b3d7393f-9b77-4cf3-83d6-77648a5f5942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán ngay'])[2]/following::button[1]</value>
      <webElementGuid>a950974b-2920-4883-ad68-01201f81ffbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền'])[1]/following::button[2]</value>
      <webElementGuid>6cd02ba1-3a66-4f45-be1c-a2d1989b62b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dịch vụ khách hàng'])[1]/preceding::button[1]</value>
      <webElementGuid>87996d99-d16a-4c7d-8b63-8532cc3c8e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div[2]/button</value>
      <webElementGuid>bd309d85-3a60-46b1-bb5d-9ea7dfaf8e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Tiếp tục mua hàng' and @type = 'button' and (text() = 'Tiếp tục mua hàng' or . = 'Tiếp tục mua hàng')]</value>
      <webElementGuid>5ecc4b52-87a5-4c9a-aa37-84a8d25e741b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
