<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>46ea5cff-45a5-4061-a92c-e3f8d9aac1e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.reduced.items-count.btn-minus.btn.btn-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a46ce9a4-73a5-467f-a4de-1eaf93293624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var result = document.getElementById('qtyItem77488103'); var qtyItem77488103 = result.value; if( !isNaN( qtyItem77488103 ) &amp;&amp; qtyItem77488103 > 1 ) result.value--;return false;</value>
      <webElementGuid>f4c0cf44-51e1-4eea-a8e5-7699ba1d37e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reduced items-count btn-minus btn btn-default</value>
      <webElementGuid>9374343e-73fb-4fa7-8172-4c3c78f3dac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>351aa48e-c2a8-4304-ad7d-18161b8fe47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>–</value>
      <webElementGuid>d04236f5-0bf5-4771-956b-1e9efef73bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-sidebars&quot;)/div[@class=&quot;evo-cart-content&quot;]/div[@class=&quot;cart_body&quot;]/div[@class=&quot;clearfix cart_product productid-77488103&quot;]/div[@class=&quot;cart_info&quot;]/div[@class=&quot;row-cart-left&quot;]/div[@class=&quot;cart_item_name&quot;]/div[1]/div[@class=&quot;cart_select&quot;]/div[@class=&quot;input-group-btn&quot;]/button[@class=&quot;reduced items-count btn-minus btn btn-default&quot;]</value>
      <webElementGuid>3c342f63-7c08-4050-bf2a-aa6d4496d451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>941ac037-d49e-4e4f-94b1-64a52dab8a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-sidebars']/div/div[2]/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>63225f57-e5a5-4221-91e9-d36e8fdaa010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng'])[1]/following::button[1]</value>
      <webElementGuid>810a3804-9b77-4385-9c9b-d9ba6f604bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Title'])[1]/following::button[1]</value>
      <webElementGuid>c8e81929-2a45-4fbe-b489-4fc7bf564913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::button[1]</value>
      <webElementGuid>c2595599-1d2a-454a-8d39-b63e82b11fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ sản phẩm'])[1]/preceding::button[2]</value>
      <webElementGuid>a58c0819-95ea-4bb5-a626-16cab534cbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>7a0161b4-7561-453c-9121-4dc0e8f8aee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '–' or . = '–')]</value>
      <webElementGuid>dfed9798-8649-42c0-8e06-ca4920e64e1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
