<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thanh ton</name>
   <tag></tag>
   <elementGuidId>b8e018e2-5d97-4ca4-884f-be49d2bb0c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-proceed-checkout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-proceed-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fe91ad0-2677-4481-be94-a6424c348c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/checkout'</value>
      <webElementGuid>51d32420-35bc-46ad-9fbe-235290e16d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>522f74eb-1754-4667-9fd9-49dcb525e870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn btn-default cart__btn-proceed-checkout</value>
      <webElementGuid>edf8b4e3-81e4-4dfa-b99c-cf5239c1cda3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-proceed-checkout</value>
      <webElementGuid>1fbb5ef9-21fa-45f4-a613-b7e84bf75827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Thanh toán</value>
      <webElementGuid>14c83501-5482-48bd-8443-b2fd84976bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanh toán</value>
      <webElementGuid>3faea8ec-b69f-4fbc-a39d-52d1b61e0156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-proceed-checkout&quot;)</value>
      <webElementGuid>c62f759b-4a39-40c3-8349-394494fcab5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-proceed-checkout']</value>
      <webElementGuid>eda6a828-737f-4928-ae46-6777c14770fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-sidebars']/div/div[3]/div[2]/button</value>
      <webElementGuid>e79f991f-4f9e-4d48-9fb6-00e4d08c41c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền:'])[1]/following::button[1]</value>
      <webElementGuid>84ffa511-1ea7-4501-ae2f-2e99d2d883d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ sản phẩm'])[2]/following::button[1]</value>
      <webElementGuid>67635e39-1882-4bcd-8c1c-77ba350b7478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm sản phẩm'])[1]/preceding::button[1]</value>
      <webElementGuid>ae12273f-0ec0-43cb-b4d7-c4d6a8cf57f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Messenger'])[1]/preceding::button[3]</value>
      <webElementGuid>982798e4-bd99-4463-b14f-32cfdc4c50a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thanh toán']/parent::*</value>
      <webElementGuid>a0d321c6-15f7-4a26-b640-163266eb705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>c604806d-4053-4d03-8987-fa39287be6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-proceed-checkout' and @title = 'Thanh toán' and (text() = 'Thanh toán' or . = 'Thanh toán')]</value>
      <webElementGuid>a901e99b-6306-4e86-b5ad-575d2f6e965f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ sản phẩm'])[1]/following::button[1]</value>
      <webElementGuid>b72b72f0-d4fb-409f-b781-9c36de8e4d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
