<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>03e0cd04-ede1-4631-b948-d208e019923e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.increase.items-count.btn-plus.btn.btn-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b335e8a0-b9c7-4bde-8038-3b4ce61bbe22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var result = document.getElementById('qtyItem77488103'); var qtyItem77488103 = result.value; if( !isNaN( qtyItem77488103 )) result.value++;return false;</value>
      <webElementGuid>9c1d2484-f9ff-4823-8334-bd3b9ed531fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>increase items-count btn-plus btn btn-default</value>
      <webElementGuid>9ddc64eb-c3a6-43b5-8054-386607cf1d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c6f9612-4a2d-417d-afdc-167da40a671e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>ed12d116-5db2-4538-8114-60a5b0671426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-sidebars&quot;)/div[@class=&quot;evo-cart-content&quot;]/div[@class=&quot;cart_body&quot;]/div[@class=&quot;clearfix cart_product productid-77488103&quot;]/div[@class=&quot;cart_info&quot;]/div[@class=&quot;row-cart-left&quot;]/div[@class=&quot;cart_item_name&quot;]/div[1]/div[@class=&quot;cart_select&quot;]/div[@class=&quot;input-group-btn&quot;]/button[@class=&quot;increase items-count btn-plus btn btn-default&quot;]</value>
      <webElementGuid>3668ba4c-2abf-4be3-8b9b-d3dde7a2eaa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>39c5e2e7-2130-4cfc-9517-6bb0fae25d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-sidebars']/div/div[2]/div/div/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>1a155d2c-e0bd-4c2d-86af-f51806c3d35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[2]/following::button[1]</value>
      <webElementGuid>d0b3e14f-21da-438d-9b22-ccc2db2b1460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng'])[1]/following::button[2]</value>
      <webElementGuid>483203ff-d099-4e51-b818-a546f3a2f81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ sản phẩm'])[1]/preceding::button[1]</value>
      <webElementGuid>158137d7-bdb9-4306-bfb3-fbbbede33f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[NHẬN TÚI CÓI THỜI TRANG] Cà Phê Bột Truyền Thống Highlands Coffee 1KG'])[2]/preceding::button[1]</value>
      <webElementGuid>8dd291a6-46c1-4a9f-a29d-44184ab2f9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>9cde41c9-6657-4440-9998-3967ab0a6fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+' or . = '+')]</value>
      <webElementGuid>928c99be-047a-4dee-8af7-40ddd3ea3506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
