<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field1</name>
   <tag></tag>
   <elementGuidId>ae7175b3-3d4b-46ae-946e-dfe8164aac9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OldPass&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
