<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tinh</name>
   <tag></tag>
   <elementGuidId>6334d539-41dd-45bf-86bd-7c641c117ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-billingProvince-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>select2-billingProvince-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
