<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xa1</name>
   <tag></tag>
   <elementGuidId>a1c9ea20-6311-4db1-9624-fe1e0fa20a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/form/div/main/div/article/div[1]/section/div[2]/div/div[7]/div/span/span[1]/span&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
